apiVersion: v1
kind: Service
metadata:
  name: extract-text-service
  namespace: anonymus
spec:
  selector:
    app: extract-text
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
