name: Build & Push Docker Images

on:
  push:
    branches: [ main, test-workflow ]
    paths:
      - 'redact-pdf/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - orchestrator
          - extract-text
          - anonymisation
          - redact-pdf
          - face-anonymisation

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./redact-pdf/${{ matrix.service }}
          file: ./redact-pdf/${{ matrix.service }}/Dockerfile
          push: true
          
          tags: |
            joreg/${{ matrix.service }}:${{ github.sha }}
            joreg/${{ matrix.service }}:latest
