name: Build & Push Docker Images

on:
  push:
    branches: [ main, test-workflow ]
    paths:
      - '**/*.py'                
      - '**/*.dvc'               
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - orchestrator
          - extract-text
          - anonymisation
          - redact-pdf
          - face-anonymisation

    env:                            
      DVC_REMOTE: modelstore
      AWS_ENDPOINT_URL: https://minio-anonymus.kube-ext.isc.heia-fr.ch
      AWS_REGION: us-east-1          

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Vérifier le fichier .dvc/config
        run: |
          ls -l .dvc/config
          cat .dvc/config

      # ────────────────────────────────────────────────
      # 1) Rétablir les artefacts DVC depuis MinIO
      # ────────────────────────────────────────────────
      - name: Setup DVC
        uses: iterative/setup-dvc@v1  
        with:
          version: "3.10.1" 
        
      - name: Cache DVC
        uses: actions/cache@v4
        with:
          path: .dvc/cache
          key: dvc-${{ github.sha }}
          restore-keys: |
            dvc-

      - name: Configure DVC remote
        run: |
          dvc remote add -d modelstore s3://ton-bucket/path
          dvc remote modify modelstore endpointurl ${{ env.AWS_ENDPOINT_URL }}
          dvc remote modify modelstore region ${{ env.AWS_REGION }}

      - name: dvc pull
        run: dvc pull -v -r ${{ env.DVC_REMOTE }}
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.MINIO_ACCESS_KEY }}   
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}

      # ────────────────────────────────────────────────
      # 2) Construction & push de l’image Docker
      # ────────────────────────────────────────────────
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}            
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            joreg/${{ matrix.service }}:${{ github.sha }}
            joreg/${{ matrix.service }}:latest
