name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build & Push Docker Images"]  
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   # déploie que si build OK
    runs-on: ubuntu-latest
    environment: production       
    steps:
   
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: azure/setup-kubectl@v3
        with:
          version: v1.27.3

     
      - name: Install kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DEV }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Debug context
        run: |
          kubectl config get-contexts
          kubectl config current-context
          kubectl get ns
      
      - name: Set images to sha tags
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          # Namespace supposé "default". Ajoute -n <ns> si besoin.
          kubectl set image deployment/orchestrator      orchestrator=joreg/orchestrator:$SHA
          kubectl set image deployment/extract-text      extract-text=joreg/extract-text:$SHA
          kubectl set image deployment/anonymisation     anonymisation=joreg/anonymisation:$SHA
          kubectl set image deployment/redact-pdf        redact-pdf=joreg/redact-pdf:$SHA
          kubectl set image deployment/face-anonymisation face-anonymisation=joreg/face-anonymisation:$SHA

   
      - name: Apply all k8s resources
        run: |
          kubectl apply -f redact-pdf/anonymisation/k8s
          kubectl apply -f redact-pdf/extract-text/k8s
          kubectl apply -f redact-pdf/redact-pdf/k8s
          kubectl apply -f redact-pdf/face-anonymisation/k8s
          kubectl apply -f redact-pdf/orchestrator/k8s
